# Generated by Django 3.1.13 on 2022-04-10 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncode', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('scode', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('type', models.CharField(choices=[('L', 'Liquor'), ('B', 'Beer'), ('M', 'Misclenious')], max_length=100)),
                ('price', models.IntegerField()),
                ('qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.brand')),
            ],
        ),
    ]
