# Generated by Django 3.1.13 on 2022-04-10 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20220410_0450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receits',
            old_name='obal',
            new_name='qty',
        ),
    ]
