# Generated by Django 3.2.16 on 2022-10-21 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyEntityClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MyModelClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo_compilato', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MyFieldsListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('field_type', models.CharField(choices=[('CustomFileField', 'Allegato (generico)'), ('CustomImageField', 'Allegato Immagine'), ('CustomSignedP7MField', 'Allegato P7M firmato'), ('CustomPDFField', 'Allegato PDF'), ('CustomSignedPdfField', 'Allegato PDF firmato'), ('CustomDataField', 'Allegato file dati (JSON, CSV, Excel)'), ('CustomHiddenField', 'Campo nascosto'), ('CustomCaptchaComplexField', 'Captcha'), ('CheckBoxField', 'Checkbox'), ('MultiCheckBoxField', 'Checkbox multi-valore'), ('BaseDateField', 'Data'), ('BaseDateTimeField', 'Data e Ora (campi separati)'), ('BaseDateTimeSimpleField', 'Data e ora (campo singolo)'), ('DateStartEndComplexField', 'Data inizio e Data fine'), ('CustomEmailField', 'E-mail'), ('CustomIPField', 'Indirizzo IP'), ('CustomComplexTableField', 'Inserimenti multipli'), ('CustomRadioBoxField', 'Lista di opzioni (checkbox)'), ('CustomSelectBoxField', 'Lista di opzioni (tendina)'), ('CustomMACField', 'MAC Address'), ('PositiveFloatField', 'Numero con virgola positivo'), ('PositiveIntegerField', 'Numero intero positivo'), ('ProtocolloField', 'Protocollo (tipo/numero/data)'), ('CustomCharField', 'Testo'), ('TextAreaField', 'Testo lungo'), ('CustomURLField', 'URL')], max_length=100)),
                ('valore', models.TextField(blank=True, default='', help_text="Viene considerato solo se si sceglie 'Menu a tendina' oppure 'Serie di Opzioni'. (Es: valore1;valore2;valore3...)", max_length=20000, verbose_name='Lista di Valori')),
                ('is_required', models.BooleanField(default=True)),
                ('aiuto', models.CharField(blank=True, default='', max_length=254)),
                ('pre_text', models.TextField(blank=True, default='')),
                ('ordinamento', models.PositiveIntegerField(blank=True, default=0, help_text="posizione nell'ordinamento")),
                ('my_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.myentityclass')),
            ],
            options={
                'ordering': ('ordinamento',),
                'abstract': False,
            },
        ),
    ]
