# Generated by Django 3.1.13 on 2022-04-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateField(auto_now_add=True)),
                ('udate', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('note', models.TextField(default=' ')),
            ],
        ),
    ]
