# Generated by Django 3.1.13 on 2022-04-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exp',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
