# Generated by Django 3.1.13 on 2022-04-24 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0002_auto_20220411_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='exp',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
            preserve_default=False,
        ),
    ]
