# Generated by Django 3.1.13 on 2022-04-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdate', models.DateField()),
                ('cdate', models.DateField(auto_now_add=True)),
                ('udate', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('amount', models.IntegerField()),
                ('roi', models.IntegerField()),
                ('status', models.CharField(choices=[('Cleared', 'Cleared'), ('Not_Cleared', 'Not Cleared')], max_length=30)),
                ('Purpose', models.TextField(blank=True, null=True)),
                ('closedate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
